name: 'dbt_selenagz_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_selenagz_project:
    # Applies to all files under models/example/
    example:
      +materialized: table

    # Applies to all files under models/mart/
    mart:
      +materialized: table
      finance:
        +schema: finance

    # Apply materialization and other settings for the intermediate models
    intermediate:
      +materialized: table  # Materialize the intermediate model as a table

    # Apply settings for the int_campaigns model
    int_campaigns:
      description: "Intermediate model that combines ad campaign data from different platforms: Adwords, Facebook, Bing, and Criteo."
      columns:
        - name: date_date
          description: "The date of the ad campaign data."
          tests:
            - not_null: {}
        - name: ads_cost
          description: "The total cost of ads in the campaign."
          tests:
            - not_null: {}
            - greater_than:
                value: 0
        - name: ads_impression
          description: "The number of impressions for the campaign."
          tests:
            - not_null: {}
            - greater_than:
                value: 0
        - name: ads_clicks
          description: "The number of clicks the campaign received."
          tests:
            - not_null: {}
            - greater_than:
                value: 0
                value: 0
        - name: ads_clicks
          description: "The number of clicks the campaign received."
          tests:
            - not_null: {}
            - greater_than:
                value: 0